vim.cmd("let g:c_formatter_42_set_equalprg=1")
vim.cmd("set tabstop=4")
vim.cmd("set shiftwidth=4")
vim.g.mapleader = " "
vim.cmd("set number")
vim.cmd("set mouse=a")
vim.cmd("set encoding=utf-8")
vim.cmd("set showmatch")
vim.cmd("set relativenumber")
vim.cmd("set showcmd")
vim.cmd("set cursorline")
vim.cmd("set ruler")
vim.cmd("set laststatus=2")
vim.cmd("let g:user42 = 'dajimene'")
vim.cmd("let g:mail42 = 'dajimene@student.42urduliz.com'")
vim.cmd("set clipboard=unnamedplus")
